[theme]
base                     = "light"
primaryColor             = "#B3361F"
backgroundColor          = "#ECEFF3"
secondaryBackgroundColor = "#E1E6EC"
textColor                = "#1B2A3A"
font                     = "sans serif"

[server]
headless = true
